//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JpGoods.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JpGoods.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;1&quot;: &quot;北海道&quot;,
        ///  &quot;2&quot;: &quot;青森県&quot;,
        ///  &quot;3&quot;: &quot;岩手県&quot;,
        ///  &quot;4&quot;: &quot;宮城県&quot;,
        ///  &quot;5&quot;: &quot;秋田県&quot;,
        ///  &quot;6&quot;: &quot;山形県&quot;,
        ///  &quot;7&quot;: &quot;福島県&quot;,
        ///  &quot;8&quot;: &quot;福井県&quot;,
        ///  &quot;9&quot;: &quot;新潟県&quot;,
        ///  &quot;10&quot;: &quot;富山県&quot;,
        ///  &quot;11&quot;: &quot;石川県&quot;,
        ///  &quot;12&quot;: &quot;山梨県&quot;,
        ///  &quot;13&quot;: &quot;長野県&quot;,
        ///  &quot;14&quot;: &quot;岐阜県&quot;,
        ///  &quot;15&quot;: &quot;静岡県&quot;,
        ///  &quot;16&quot;: &quot;愛知県&quot;,
        ///  &quot;17&quot;: &quot;東京都&quot;,
        ///  &quot;18&quot;: &quot;神奈川県&quot;,
        ///  &quot;19&quot;: &quot;千葉県&quot;,
        ///  &quot;20&quot;: &quot;埼玉県&quot;,
        ///  &quot;21&quot;: &quot;群馬県&quot;,
        ///  &quot;22&quot;: &quot;栃木県&quot;,
        ///  &quot;23&quot;: &quot;茨城県&quot;,
        ///  &quot;24&quot;: &quot;三重県&quot;,
        ///  &quot;25&quot;: &quot;兵庫県&quot;,
        ///  &quot;26&quot;: &quot;奈良県&quot;,
        ///  &quot;27&quot;: &quot;大阪府&quot;,
        ///  &quot;28&quot;: &quot;滋賀県&quot;,
        ///  &quot;29&quot;: ....
        /// </summary>
        internal static string areas {
            get {
                return ResourceManager.GetString("areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;0101&quot;: &quot;Tシャツ(半袖 / ノースリーブ)&quot;,
        ///  &quot;0102&quot;: &quot;Tシャツ(長袖 / 五丈 / 七丈)&quot;,
        ///  &quot;0103&quot;: &quot;カットソー(半袖 / ノースリーブ)&quot;,
        ///  &quot;0104&quot;: &quot;カットソー(長袖 / 五丈 / 七丈)&quot;,
        ///  &quot;0105&quot;: &quot;シャツ / ブラウス(半袖 / ノースリーブ)&quot;,
        ///  &quot;0106&quot;: &quot;シャツ / ブラウス(長袖 / 五丈 / 七丈)&quot;,
        ///  &quot;0107&quot;: &quot;ポロシャツ&quot;,
        ///  &quot;0108&quot;: &quot;ニット / セーター&quot;,
        ///  &quot;0109&quot;: &quot;パーカー&quot;,
        ///  &quot;0110&quot;: &quot;カーディガン&quot;,
        ///  &quot;0111&quot;: &quot;トレーナー / スウェット&quot;,
        ///  &quot;0112&quot;: &quot;キャミソール&quot;,
        ///  &quot;0113&quot;: &quot;タンクトップ&quot;,
        ///  &quot;0114&quot;: &quot;ベアトップ / チューブトップ&quot;,
        ///  &quot;0115&quot;: &quot;ホルターネック&quot;,
        ///  &quot;0116&quot;: &quot;チュニック&quot;,
        ///  &quot;0117&quot;: &quot;ベスト / ジレ&quot;,
        ///  &quot;0118&quot;: &quot;アンサンブル&quot;,
        ///  &quot;0119&quot;: &quot;ボレロ&quot;,
        ///  &quot;0201&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;0&quot;: &quot;指定なし&quot;,
        ///  &quot;1&quot;: &quot;1～2日で発送&quot;,
        ///  &quot;2&quot;: &quot;2～3日で発送&quot;,
        ///  &quot;3&quot;: &quot;4～7日で発送&quot;,
        ///  &quot;5&quot;: &quot;発送は週末のみ&quot;,
        ///  &quot;6&quot;: &quot;発送は平日のみ&quot;
        ///}.
        /// </summary>
        internal static string shipday {
            get {
                return ResourceManager.GetString("shipday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;0&quot;: &quot;未定&quot;,
        ///  &quot;1&quot;: &quot;普通郵便(定型/定型外)&quot;,
        ///  &quot;2&quot;: &quot;ゆうパック&quot;,
        ///  &quot;3&quot;: &quot;レターパックプラス&quot;,
        ///  &quot;4&quot;: &quot;レターパックライト&quot;,
        ///  &quot;5&quot;: &quot;メール便/ゆうメール&quot;,
        ///  &quot;6&quot;: &quot;ヤマト宅急便&quot;,
        ///  &quot;7&quot;: &quot;ポスパケット&quot;,
        ///  &quot;8&quot;: &quot;はこBOON&quot;,
        ///  &quot;11&quot;: &quot;ゆうパック着払い&quot;,
        ///  &quot;12&quot;: &quot;ヤマト宅急便&quot;,
        ///  &quot;13&quot;: &quot;ポスパケット&quot;,
        ///  &quot;17&quot;: &quot;飛脚宅急便&quot;,
        ///  &quot;19&quot;: &quot;ゆうメール着払い&quot;,
        ///  &quot;81&quot;: &quot;クリックポスト&quot;,
        ///  &quot;82&quot;: &quot;飛脚メール便&quot;,
        ///  &quot;83&quot;: &quot;飛脚宅急便&quot;,
        ///  &quot;84&quot;: &quot;カンガルーミニ便&quot;,
        ///  &quot;85&quot;: &quot;宅急便コンパクト&quot;,
        ///  &quot;86&quot;: &quot;ゆうメール&quot;,
        ///  &quot;87&quot;: &quot;スマートレター&quot;
        ///}.
        /// </summary>
        internal static string shippings {
            get {
                return ResourceManager.GetString("shippings", resourceCulture);
            }
        }
    }
}
